# Generated by Django 4.2 on 2026-03-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='market',
            field=models.CharField(choices=[('NIFTY', 'Nifty 50'), ('USA', 'US Stocks')], default='USA', max_length=10),
        ),
    ]
