# Generated by Django 4.2 on 2026-03-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_high_price_stock_low_price_stock_open_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBronze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(max_length=1000)),
                ('publish_time', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='change_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volatility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NewsSilver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_title', models.TextField()),
                ('cleaned_content', models.TextField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('bronze', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='silver', to='stocks.newsbronze')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_silver', to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='NewsGold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('recommendation', models.CharField(max_length=20)),
                ('reasoning', models.TextField()),
                ('overall_sentiment', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news_gold', to='stocks.stock')),
            ],
        ),
        migrations.AddField(
            model_name='newsbronze',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_bronze', to='stocks.stock'),
        ),
    ]
