# Generated by Django 4.2 on 2026-03-24 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0003_stock_high_price_stock_low_price_stock_open_price_and_more'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('group_type', models.CharField(choices=[('SECTOR', 'Sector-based'), ('CUSTOM', 'Custom Portfolio')], default='CUSTOM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.portfoliogroup'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'stock', 'group')},
        ),
    ]
